version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"

    links:
      - redis:redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

