version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  web:
    build:
      context: .
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    depends_on:
      - redis
    volumes:
      - .:/app
